### ISSUE TITLE
인터파크 데이터 중복 처리

### ISSUE THREAD

**Issue by jinspark-lab** [f-lab-edu/Oasis#15]
홈 / 추천 / 디렉터 추천 등을 서비스에서 사용할 수 있을만한 형태로 데이터 가공 필요

**Comment by dev-msj** [comment]
Wiki 변경에 대한 pull request는 지원하지 않는 것 같아 변경사항을 댓글로 남겨놓습니다!

[DB_Schema](https://github.com/f-lab-edu/Oasis/wiki/DB-Schema/d12dbbaba59cdc26b656f35b099d0e0c299dcca9) : BOOK_LIST 수정 - BOOK_ID에 ISBN 사용, TRANSLATOR 추가

**Comment by jinspark-lab** [comment]
ISBN 사용
