### ISSUE TITLE
Spring Boot 프로젝트 세팅

### ISSUE THREAD

**Issue by jinspark-lab** [f-lab-edu/Oasis#7]
Spring Boot 기본 프로젝트 환경 세팅

Include:
- Sprint Boot
- MyBatis
- JDBC ConnectionPool Library (HikaryCP 추천)
- log4j
- Lombok
- JUnit

**Comment by dev-msj** [comment]
https://github.com/f-lab-edu/Oasis/commit/abba10813686cddba196a88fb1ee3822beb67d2d

프로젝트 생성했습니다.

**Comment by jinspark-lab** [comment]
LGTM
