### ISSUE TITLE
Interpark Mock Data 저장

### ISSUE THREAD

**Issue by jinspark-lab** [f-lab-edu/Oasis#8]
InterPark API 로부터 Mock Data 로드

**Comment by jinspark-lab** [comment]
https://github.com/f-lab-edu/Oasis/issues/15

**Comment by dev-msj** [comment]
mocking data 공유드립니다!

[dump-oasis.tar.gz](https://github.com/f-lab-edu/Oasis/files/10445353/dump-oasis.tar.gz)

**Comment by jinspark-lab** [comment]
확인
